module.exports = topicos = [
  {path: '/thome_lucas/Inacia_Cozinha/ativo', type: 'ativo'},
  {path: '/thome_lucas/Casa_Cozinha/ativo', type: 'ativo'},
  {path: '/kau/piscina/ativo', type: 'ativo'},
  {path: '/thome_lucas/caixa/ativo', type: 'ativo'},
  {path: '/thome_lucas/portao/ativo', type: 'ativo'},
  {path: '/tome/alarme/ativo', type: 'ativo'},
  {path: '/ricardo21/casa/ativo', type: 'ativo'},
  {path: '/thome_lucas/reles/ativo', type: 'ativo'},
  {path: '/thome_lucas/dimmers/ativo', type: 'ativo'},
  {path: '/monitv1/wynmax_telecom/pop_inhuma/ativo', type: 'ativo'},
  {path: '/micks/cortinas/ativo', type: 'ativo'},
  {path: '/wynmax_telecom/caixa/ativo', type: 'ativo'},
  {path: '/monitv1/wynmax_telecom/pop_baixas/ativo', type: 'ativo'},
  {path: '/monitv1/mnet/mutans/ativo', type: 'ativo'},
  {path: '/miniv1/mnet/pop1/ativo', type: 'ativo'},
  {path: '/josival/fonte_vdc/ativo', type: 'ativo'},
  {path: '/neto_paula/monit/ativo', type: 'ativo'},
  {path: '/miniv1/mnet/minador/ativo', type: 'ativo'},
  {path: '/miniv1/mnet/lagoa_pedra/ativo', type: 'ativo'},
  {path: '/atlantica_telecom/base_x/ativo', type: 'ativo'},
  {path: '/miniv1/ji/donizete/ativo', type: 'ativo'},
  {path: '/miniv1/cybernet/porto_novo/ativo', type: 'ativo'},
  {path: '/josival/serv4587/ativo', type: 'ativo'}
]